### ISSUE TITLE
Crash w/ Everlasting Abilities

### ISSUE THREAD

**Issue by WenXin20** [ArtixAllMighty/PublicGuiAnnouncement#1]
#### Issue type:

- :bug: Bug

____

#### Short description:

 I received this crash after creating a new world and adding this mod, Public GUI Announcement. 

#### Steps to reproduce the problem:

1. Install Everlasting Abilities & Cyclops Core
2. Create a new world

#### Expected behaviour:

 No crashes and/or custom support for this mod.

____

#### Versions:

- Public GUI Announcement: v1.0.1.0
- [Everlasting Abilities](https://www.curseforge.com/minecraft/mc-mods/everlastingabilities): v1.5.2
- Minecraft: v1.14.4
- Forge: v28.1.1

#### Log file:

[Crash Report](https://gist.github.com/WenXin20/3272d517e9f33bf45127154289f7e85b)

See the following for a bit more info: CyclopsMC/EverlastingAbilities#131

**Comment by AbsolemJackdaw** [comment]
issue adressed.
fixed in e00fa5f5

**Comment by WenXin20** [comment]
I'm getting a similar issue again, but the game gets stuck on the joining world screen instead of crashing.
Forge v28.1.10
Everlasting Abilities v1.5.3
Cyclops Core v1.5.2
PGA v1.0.1.1

Full Log: [latest.zip](https://github.com/ArtixAllMighty/PublicGuiAnnouncement/files/3634260/latest.zip)
```
[22:57:14] [Server thread/ERROR]: Exception caught during firing event: A given capability is null
	Index: 3
	Listeners:
		0: NORMAL
		1: ASM: class com.robertx22.mine_and_slash.onevent.entity.OnTrackEntity onEntityTrack(Lnet/minecraftforge/event/entity/player/PlayerEvent$StartTracking;)V
		2: ASM: class gigaherz.toolbelt.common.BeltEvents startTracking(Lnet/minecraftforge/event/entity/player/PlayerEvent$StartTracking;)V
		3: ASM: subaraki.pga.event.PlayerEventHandler@520d6866 playerTracking(Lnet/minecraftforge/event/entity/player/PlayerEvent$StartTracking;)V
		4: ASM: top.theillusivec4.curios.common.event.EventHandlerCurios@4aa2fe11 onPlayerStartTracking(Lnet/minecraftforge/event/entity/player/PlayerEvent$StartTracking;)V
		5: ASM: tschipp.carryon.common.event.ItemEvents@24581a68 onEntityStartTracking(Lnet/minecraftforge/event/entity/player/PlayerEvent$StartTracking;)V
		6: ASM: gigaherz.toolbelt.slot.BeltExtensionSlot$EventHandlers@603a44ea track(Lnet/minecraftforge/event/entity/player/PlayerEvent$StartTracking;)V
java.lang.NullPointerException: A given capability is null
	at java.util.Objects.requireNonNull(Objects.java:228)
	at org.cyclops.cyclopscore.modcompat.capabilities.DefaultCapabilityProvider.getCapability(DefaultCapabilityProvider.java:38)
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:102)
	at net.minecraftforge.common.capabilities.CapabilityProvider.getCapability(CapabilityProvider.java:118)
	at net.minecraft.entity.LivingEntity.getCapability(LivingEntity.java:2890)
	at net.minecraft.entity.player.PlayerEntity.getCapability(PlayerEntity.java:2098)
	at subaraki.pga.capability.ScreenData.get(ScreenData.java:31)
	at subaraki.pga.event.PlayerEventHandler.playerTracking(PlayerEventHandler.java:22)
	at net.minecraftforge.eventbus.ASMEventHandler_1172_PlayerEventHandler_playerTracking_StartTracking.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.event.ForgeEventFactory.onStartEntityTracking(ForgeEventFactory.java:307)
	at net.minecraft.world.TrackedEntity.func_219455_b(TrackedEntity.java:193)
	at net.minecraft.world.server.ChunkManager$EntityTracker.func_219400_b(ChunkManager.java:1123)
	at net.minecraft.world.server.ChunkManager.func_219183_a(ChunkManager.java:831)
	at net.minecraft.world.server.ServerChunkProvider.func_217221_a(SourceFile:475)
	at net.minecraft.network.play.ServerPlayNetHandler.func_147347_a(ServerPlayNetHandler.java:759)
	at net.minecraft.network.play.client.CPlayerPacket.func_148833_a(SourceFile:126)
	at net.minecraft.network.play.client.CPlayerPacket$PositionRotationPacket.func_148833_a(SourceFile:18)
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
	at net.minecraft.network.PacketThreadUtil$$Lambda$11268/1011571775.run(Unknown Source)
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699)
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:679)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626)
	at java.lang.Thread.run(Thread.java:745)
```
![2019-09-19_23 36 07](https://user-images.githubusercontent.com/12000593/65300162-295b1f80-db38-11e9-94d4-90ed051b4bea.png)

**Comment by jkwphysics** [comment]
Seem to be having the same crash with a custom modpack. I haven't been able to isolate the conflict though since the ones that show in the stack trace (RFTools mods) work ok with Everlasting Abilities when they are the only mods in a pack. Is it still possible for this to be on RFTools or some other mod?

Forge v39.0.10
Everlasting Abilities v1.7.3
Cyclops Core v1.12.1

https://pastebin.com/4fqWUvUT

**Comment by AbsolemJackdaw** [comment]
cyclops core checks if capabilities are not null. 
given pga isnt in the log, i'd try cyclopse core and rftools to see if it passes. I'll be double checking my code and contacting mcjty to get some info on his end. 

thanks for the report !

**Comment by AbsolemJackdaw** [comment]
this issue is being looked at by mcjty and will be fixed in a close future release.
